trigger:
  batch: "true"
  branches:
    include:
      - dev
      - qa
      - uat
      - master

pr:
  autoCancel: "false"
  branches:
    include:
      - dev
      - qa
      - uat
      - master
      
jobs:
- job: ProdDeploy
  displayName: Production Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
    - task: UseNode@1
    - bash: 
        npm install  --global sfdx-cli@7.45.1
      displayName: Install Salesforce CLI
    - bash: 
        sfdx force:auth:jwt:grant --clientid $(prodClientId) --jwtkeyfile ./server.key --username $(prodUserName) --instanceurl $(ProdInstanceUrl) -a prod
      displayName: Authorize salesforce org
    - bash: 
        sfdx force:source:deploy -l RunLocalTests -p ./force-app -u prod -w 10
      displayName: Deploying  Metadata to the Org

- job: devsandboxProdDeploy
  displayName: UAT Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/uat'))
  steps:
    - task: UseNode@1
    - bash: 
        npm install  --global sfdx-cli@7.45.1
      displayName: Install Salesforce CLI
    - bash: 
        sfdx force:auth:jwt:grant --clientid $(uatClientId) --jwtkeyfile ./server.key --username $(uatUserName) --instanceurl $(ProdInstanceUrl) -a prod
      displayName: Authorize salesforce org
    - bash: 
        sfdx force:source:deploy -l RunLocalTests -p ./force-app -u prod -w 10
      displayName: Deploying  Metadata to the Org

- job: QADeploy
  displayName: QA Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/qa'))
  steps:
    - task: UseNode@1
    - bash: 
        npm install  --global sfdx-cli@7.45.1
      displayName: Install Salesforce CLI
    - bash: 
        sfdx force:auth:jwt:grant --clientid $(qaClient) --jwtkeyfile ./server.key --username $(qaUsername) --instanceurl $(ProdInstanceUrl) -a prod
      displayName: Authorize salesforce org
    - bash: 
        sfdx force:source:deploy -l RunLocalTests -p ./force-app -u prod -w 10
      displayName: Deploying  Metadata to the Org

- job: devsandboxDeploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/devSandbox'))
  steps:
    - task: UseNode@1
    - bash: 
        npm install  --global sfdx-cli@7.45.1
      displayName: Install Salesforce CLI
    - bash: 
        sfdx force:auth:jwt:grant --clientid $(devSanboxKey) --jwtkeyfile ./server.key --username $(devSandbox) --instanceurl $(ProdInstanceUrl) -a prod
      displayName: Authorize salesforce org
    - bash: 
        sfdx force:source:deploy -l RunLocalTests -p ./force-app -u prod -w 10
      displayName: Deploying Metadata to the Org      